```sql
DELETE FROM public.hosting_plans WHERE category = 'VPS';

INSERT INTO public.hosting_plans (name, category, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Silicon Valley', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'North America', '🇺🇸', 'Deploy your applications in Silicon Valley with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Silicon Valley', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'North America', '🇺🇸', 'Deploy your applications in Silicon Valley with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Silicon Valley', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'North America', '🇺🇸', 'Deploy your applications in Silicon Valley with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Moscow', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇷🇺', 'Deploy your applications in Moscow with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Moscow', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇷🇺', 'Deploy your applications in Moscow with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Moscow', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇷🇺', 'Deploy your applications in Moscow with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Frankfurt', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇩🇪', 'Deploy your applications in Frankfurt with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Frankfurt', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇩🇪', 'Deploy your applications in Frankfurt with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Frankfurt', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇩🇪', 'Deploy your applications in Frankfurt with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Jeddah', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇸🇦', 'Deploy your applications in Jeddah with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Jeddah', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇸🇦', 'Deploy your applications in Jeddah with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Jeddah', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇸🇦', 'Deploy your applications in Jeddah with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Washington', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'North America', '🇺🇸', 'Deploy your applications in Washington with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Washington', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'North America', '🇺🇸', 'Deploy your applications in Washington with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Washington', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'North America', '🇺🇸', 'Deploy your applications in Washington with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Athens', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇬🇷', 'Deploy your applications in Athens with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Athens', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇬🇷', 'Deploy your applications in Athens with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Athens', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇬🇷', 'Deploy your applications in Athens with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bahrain', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇧🇭', 'Deploy your applications in Bahrain with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bahrain', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇧🇭', 'Deploy your applications in Bahrain with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bahrain', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇧🇭', 'Deploy your applications in Bahrain with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Sofia', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇧🇬', 'Deploy your applications in Sofia with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Sofia', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇧🇬', 'Deploy your applications in Sofia with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Sofia', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇧🇬', 'Deploy your applications in Sofia with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'London', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇬🇧', 'Deploy your applications in London with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'London', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇬🇧', 'Deploy your applications in London with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'London', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇬🇧', 'Deploy your applications in London with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Doha', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇶🇦', 'Deploy your applications in Doha with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Doha', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇶🇦', 'Deploy your applications in Doha with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Doha', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇶🇦', 'Deploy your applications in Doha with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Tokyo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'East Asia', '🇯🇵', 'Deploy your applications in Tokyo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Tokyo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'East Asia', '🇯🇵', 'Deploy your applications in Tokyo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Tokyo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'East Asia', '🇯🇵', 'Deploy your applications in Tokyo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bangkok', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇹🇭', 'Deploy your applications in Bangkok with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bangkok', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇹🇭', 'Deploy your applications in Bangkok with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bangkok', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇹🇭', 'Deploy your applications in Bangkok with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Hanoi', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Hanoi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Hanoi', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Hanoi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Hanoi', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Hanoi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Phnom Penh', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇰🇭', 'Deploy your applications in Phnom Penh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Phnom Penh', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇰🇭', 'Deploy your applications in Phnom Penh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Phnom Penh', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇰🇭', 'Deploy your applications in Phnom Penh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Ho Chi Minh', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Ho Chi Minh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Ho Chi Minh', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Ho Chi Minh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Ho Chi Minh', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇻🇳', 'Deploy your applications in Ho Chi Minh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Marseille', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇫🇷', 'Deploy your applications in Marseille with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Marseille', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇫🇷', 'Deploy your applications in Marseille with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Marseille', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇫🇷', 'Deploy your applications in Marseille with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Manila', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇵🇭', 'Deploy your applications in Manila with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Manila', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇵🇭', 'Deploy your applications in Manila with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Manila', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇵🇭', 'Deploy your applications in Manila with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Johannesburg', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Africa', '🇿🇦', 'Deploy your applications in Johannesburg with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Johannesburg', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Africa', '🇿🇦', 'Deploy your applications in Johannesburg with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Johannesburg', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Africa', '🇿🇦', 'Deploy your applications in Johannesburg with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Taipei', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'East Asia', '🇹🇼', 'Deploy your applications in Taipei with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Taipei', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'East Asia', '🇹🇼', 'Deploy your applications in Taipei with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Taipei', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'East Asia', '🇹🇼', 'Deploy your applications in Taipei with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Hong Kong', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'East Asia', '🇭🇰', 'Deploy your applications in Hong Kong with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Hong Kong', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'East Asia', '🇭🇰', 'Deploy your applications in Hong Kong with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Hong Kong', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'East Asia', '🇭🇰', 'Deploy your applications in Hong Kong with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Istanbul', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Europe', '🇹🇷', 'Deploy your applications in Istanbul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Istanbul', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Europe', '🇹🇷', 'Deploy your applications in Istanbul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Istanbul', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Europe', '🇹🇷', 'Deploy your applications in Istanbul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kuwait City', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇰🇼', 'Deploy your applications in Kuwait City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kuwait City', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇰🇼', 'Deploy your applications in Kuwait City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kuwait City', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇰🇼', 'Deploy your applications in Kuwait City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Dubai', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇦🇪', 'Deploy your applications in Dubai with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Dubai', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇦🇪', 'Deploy your applications in Dubai with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Dubai', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇦🇪', 'Deploy your applications in Dubai with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Seoul', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'East Asia', '🇰🇷', 'Deploy your applications in Seoul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Seoul', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'East Asia', '🇰🇷', 'Deploy your applications in Seoul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Seoul', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'East Asia', '🇰🇷', 'Deploy your applications in Seoul with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Riyadh', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇸🇦', 'Deploy your applications in Riyadh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Riyadh', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇸🇦', 'Deploy your applications in Riyadh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Riyadh', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇸🇦', 'Deploy your applications in Riyadh with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Muscat', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇴🇲', 'Deploy your applications in Muscat with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Muscat', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇴🇲', 'Deploy your applications in Muscat with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Muscat', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇴🇲', 'Deploy your applications in Muscat with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Yangon', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇲🇲', 'Deploy your applications in Yangon with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Yangon', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇲🇲', 'Deploy your applications in Yangon with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Yangon', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇲🇲', 'Deploy your applications in Yangon with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kathmandu', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South Asia', '🇳🇵', 'Deploy your applications in Kathmandu with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kathmandu', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South Asia', '🇳🇵', 'Deploy your applications in Kathmandu with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kathmandu', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South Asia', '🇳🇵', 'Deploy your applications in Kathmandu with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Baghdad', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Middle East', '🇮🇶', 'Deploy your applications in Baghdad with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Baghdad', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Middle East', '🇮🇶', 'Deploy your applications in Baghdad with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Baghdad', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Middle East', '🇮🇶', 'Deploy your applications in Baghdad with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Dhaka', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South Asia', '🇧🇩', 'Deploy your applications in Dhaka with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Dhaka', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South Asia', '🇧🇩', 'Deploy your applications in Dhaka with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Dhaka', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South Asia', '🇧🇩', 'Deploy your applications in Dhaka with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Singapore', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇸🇬', 'Deploy your applications in Singapore with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Singapore', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇸🇬', 'Deploy your applications in Singapore with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Singapore', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇸🇬', 'Deploy your applications in Singapore with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kuala Lumpur', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇲🇾', 'Deploy your applications in Kuala Lumpur with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kuala Lumpur', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇲🇾', 'Deploy your applications in Kuala Lumpur with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kuala Lumpur', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇲🇾', 'Deploy your applications in Kuala Lumpur with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Jakarta', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Southeast Asia', '🇮🇩', 'Deploy your applications in Jakarta with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Jakarta', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Southeast Asia', '🇮🇩', 'Deploy your applications in Jakarta with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Jakarta', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Southeast Asia', '🇮🇩', 'Deploy your applications in Jakarta with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Buenos Aires', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South America', '🇦🇷', 'Deploy your applications in Buenos Aires with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Buenos Aires', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South America', '🇦🇷', 'Deploy your applications in Buenos Aires with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Buenos Aires', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South America', '🇦🇷', 'Deploy your applications in Buenos Aires with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Cairo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'Africa', '🇪🇬', 'Deploy your applications in Cairo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Cairo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'Africa', '🇪🇬', 'Deploy your applications in Cairo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Cairo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'Africa', '🇪🇬', 'Deploy your applications in Cairo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bogota', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South America', '🇨🇴', 'Deploy your applications in Bogota with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bogota', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South America', '🇨🇴', 'Deploy your applications in Bogota with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bogota', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South America', '🇨🇴', 'Deploy your applications in Bogota with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Karachi', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South Asia', '🇵🇰', 'Deploy your applications in Karachi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Karachi', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South Asia', '🇵🇰', 'Deploy your applications in Karachi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Karachi', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South Asia', '🇵🇰', 'Deploy your applications in Karachi with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Santiago', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South America', '🇨🇱', 'Deploy your applications in Santiago with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Santiago', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South America', '🇨🇱', 'Deploy your applications in Santiago with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Santiago', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South America', '🇨🇱', 'Deploy your applications in Santiago with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Sao Paulo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'South America', '🇧🇷', 'Deploy your applications in Sao Paulo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Sao Paulo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'South America', '🇧🇷', 'Deploy your applications in Sao Paulo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Sao Paulo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'South America', '🇧🇷', 'Deploy your applications in Sao Paulo with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro'),

('Basic VPS', 'VPS', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Mexico City', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', true, 10, 'North America', '🇲🇽', 'Deploy your applications in Mexico City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Professional VPS', 'VPS', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Mexico City', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', true, 20, 'North America', '🇲🇽', 'Deploy your applications in Mexico City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Enterprise VPS', 'VPS', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Mexico City', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', true, 30, 'North America', '🇲🇽', 'Deploy your applications in Mexico City with premium VPS hosting featuring dedicated resources and enterprise-grade infrastructure.', 'Pro');
```