DELETE FROM public.hosting_plans WHERE category = 'VPS';

INSERT INTO public.hosting_plans (
    name, category, subcategory, region, flag_icon, page_description, plan_type,
    ram, cpu, storage, bandwidth, location, os_type,
    price_monthly, price_yearly, sale_enabled, order_url, visible, sort_order,
    created_at, updated_at
) VALUES
('Basic VPS', 'VPS', NULL, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo, Egypt with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Cairo', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/cairo-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo, Egypt with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Cairo', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/cairo-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo, Egypt with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Cairo', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/cairo-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg, South Africa with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Johannesburg', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/johannesburg-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg, South Africa with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Johannesburg', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/johannesburg-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg, South Africa with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Johannesburg', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/johannesburg-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Hong Kong', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/hong-kong-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Hong Kong', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/hong-kong-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Hong Kong', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/hong-kong-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul, South Korea with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Seoul', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/seoul-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul, South Korea with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Seoul', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/seoul-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul, South Korea with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Seoul', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/seoul-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei, Taiwan with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Taipei', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/taipei-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei, Taiwan with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Taipei', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/taipei-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei, Taiwan with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Taipei', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/taipei-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo, Japan with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Tokyo', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/tokyo-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo, Japan with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Tokyo', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/tokyo-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo, Japan with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Tokyo', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/tokyo-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens, Greece with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Athens', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/athens-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens, Greece with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Athens', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/athens-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens, Greece with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Athens', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/athens-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt, Germany with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Frankfurt', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/frankfurt-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt, Germany with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Frankfurt', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/frankfurt-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt, Germany with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Frankfurt', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/frankfurt-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇬🇧', 'High-performance VPS hosting in London, UK with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'London', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/london-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇬🇧', 'High-performance VPS hosting in London, UK with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'London', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/london-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇬🇧', 'High-performance VPS hosting in London, UK with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'London', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/london-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille, France with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Marseille', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/marseille-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille, France with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Marseille', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/marseille-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille, France with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Marseille', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/marseille-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow, Russia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Moscow', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/moscow-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow, Russia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Moscow', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/moscow-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow, Russia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Moscow', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/moscow-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia, Bulgaria with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Sofia', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/sofia-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia, Bulgaria with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Sofia', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/sofia-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia, Bulgaria with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Sofia', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/sofia-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad, Iraq with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Baghdad', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/baghdad-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad, Iraq with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Baghdad', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/baghdad-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad, Iraq with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Baghdad', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/baghdad-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bahrain', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/bahrain-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bahrain', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/bahrain-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bahrain', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/bahrain-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha, Qatar with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Doha', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/doha-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha, Qatar with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Doha', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/doha-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha, Qatar with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Doha', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/doha-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai, UAE with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Dubai', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/dubai-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai, UAE with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Dubai', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/dubai-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai, UAE with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Dubai', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/dubai-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul, Turkey with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Istanbul', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/istanbul-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul, Turkey with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Istanbul', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/istanbul-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul, Turkey with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Istanbul', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/istanbul-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Jeddah', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/jeddah-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Jeddah', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/jeddah-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Jeddah', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/jeddah-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City, Kuwait with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kuwait City', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuwait-city-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City, Kuwait with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kuwait City', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuwait-city-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City, Kuwait with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kuwait City', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuwait-city-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat, Oman with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Muscat', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/muscat-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat, Oman with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Muscat', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/muscat-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat, Oman with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Muscat', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/muscat-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Riyadh', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/riyadh-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Riyadh', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/riyadh-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh, Saudi Arabia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Riyadh', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/riyadh-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City, Mexico with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Mexico City', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/mexico-city-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City, Mexico with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Mexico City', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/mexico-city-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City, Mexico with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Mexico City', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/mexico-city-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley, USA with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Silicon Valley', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/silicon-valley-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley, USA with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Silicon Valley', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/silicon-valley-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley, USA with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Silicon Valley', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/silicon-valley-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington, USA with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Washington', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/washington-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington, USA with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Washington', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/washington-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington, USA with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Washington', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/washington-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney, Australia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Sydney', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/sydney-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney, Australia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Sydney', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/sydney-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney, Australia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Sydney', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/sydney-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota, Colombia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bogota', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/bogota-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota, Colombia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bogota', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/bogota-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota, Colombia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bogota', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/bogota-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires, Argentina with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Buenos Aires', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/buenos-aires-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires, Argentina with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Buenos Aires', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/buenos-aires-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires, Argentina with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Buenos Aires', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/buenos-aires-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago, Chile with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Santiago', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/santiago-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago, Chile with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Santiago', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/santiago-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago, Chile with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Santiago', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/santiago-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo, Brazil with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'São Paulo', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/sao-paulo-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo, Brazil with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'São Paulo', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/sao-paulo-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo, Brazil with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'São Paulo', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/sao-paulo-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka, Bangladesh with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Dhaka', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/dhaka-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka, Bangladesh with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Dhaka', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/dhaka-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka, Bangladesh with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Dhaka', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/dhaka-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi, Pakistan with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Karachi', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/karachi-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi, Pakistan with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Karachi', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/karachi-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi, Pakistan with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Karachi', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/karachi-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu, Nepal with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kathmandu', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/kathmandu-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu, Nepal with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kathmandu', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/kathmandu-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu, Nepal with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kathmandu', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/kathmandu-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai, India with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Mumbai', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/mumbai-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai, India with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Mumbai', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/mumbai-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai, India with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Mumbai', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/mumbai-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok, Thailand with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Bangkok', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/bangkok-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok, Thailand with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Bangkok', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/bangkok-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok, Thailand with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Bangkok', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/bangkok-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Hanoi', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/hanoi-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Hanoi', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/hanoi-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Hanoi', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/hanoi-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Ho Chi Minh City', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/ho-chi-minh-city-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Ho Chi Minh City', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/ho-chi-minh-city-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City, Vietnam with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Ho Chi Minh City', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/ho-chi-minh-city-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta, Indonesia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Jakarta', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/jakarta-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta, Indonesia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Jakarta', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/jakarta-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta, Indonesia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Jakarta', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/jakarta-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur, Malaysia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Kuala Lumpur', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuala-lumpur-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur, Malaysia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Kuala Lumpur', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuala-lumpur-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur, Malaysia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Kuala Lumpur', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/kuala-lumpur-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila, Philippines with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Manila', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/manila-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila, Philippines with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Manila', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/manila-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila, Philippines with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Manila', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/manila-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh, Cambodia with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Phnom Penh', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/phnom-penh-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh, Cambodia with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Phnom Penh', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/phnom-penh-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh, Cambodia with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Phnom Penh', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/phnom-penh-pro', TRUE, 30, NOW(), NOW()),

('Basic VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon, Myanmar with dedicated resources and enterprise-grade infrastructure.', 'Basic', '2GB RAM', '1 vCPU', '30GB SSD', '1TB Bandwidth', 'Yangon', 'Linux', 9.99, 7.99, FALSE, 'https://portal.qiwhost.com/order/vps/yangon-basic', TRUE, 10, NOW(), NOW()),
('Standard VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon, Myanmar with dedicated resources and enterprise-grade infrastructure.', 'Standard', '4GB RAM', '2 vCPU', '60GB SSD', '2TB Bandwidth', 'Yangon', 'Linux', 19.99, 15.99, FALSE, 'https://portal.qiwhost.com/order/vps/yangon-standard', TRUE, 20, NOW(), NOW()),
('Pro VPS', 'VPS', NULL, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon, Myanmar with dedicated resources and enterprise-grade infrastructure.', 'Pro', '8GB RAM', '4 vCPU', '120GB SSD', '4TB Bandwidth', 'Yangon', 'Linux', 39.99, 31.99, FALSE, 'https://portal.qiwhost.com/order/vps/yangon-pro', TRUE, 30, NOW(), NOW());