```sql
-- Delete existing VPS plans to ensure a clean slate for these 40 cities
DELETE FROM public.hosting_plans WHERE category = 'VPS';

-- Insert 3 VPS plans for each of the 40 cities

-- Africa
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Cairo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Cairo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Cairo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Africa', '🇪🇬', 'High-performance VPS hosting in Cairo with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Johannesburg', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Johannesburg', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Johannesburg', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Africa', '🇿🇦', 'High-performance VPS hosting in Johannesburg with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- East Asia
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Hong Kong', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Hong Kong', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Hong Kong', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'East Asia', '🇭🇰', 'High-performance VPS hosting in Hong Kong with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Seoul', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Seoul', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Seoul', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'East Asia', '🇰🇷', 'High-performance VPS hosting in Seoul with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Taipei', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Taipei', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Taipei', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'East Asia', '🇹🇼', 'High-performance VPS hosting in Taipei with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Tokyo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Tokyo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Tokyo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'East Asia', '🇯🇵', 'High-performance VPS hosting in Tokyo with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- Europe
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Athens', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Athens', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Athens', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇬🇷', 'High-performance VPS hosting in Athens with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Frankfurt', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Frankfurt', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Frankfurt', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇩🇪', 'High-performance VPS hosting in Frankfurt with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'London', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇬🇧', 'High-performance VPS hosting in London with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'London', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇬🇧', 'High-performance VPS hosting in London with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'London', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇬🇧', 'High-performance VPS hosting in London with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Marseille', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Marseille', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Marseille', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇫🇷', 'High-performance VPS hosting in Marseille with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Moscow', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Moscow', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Moscow', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇷🇺', 'High-performance VPS hosting in Moscow with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Sofia', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Sofia', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Sofia', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Europe', '🇧🇬', 'High-performance VPS hosting in Sofia with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- Middle East
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Baghdad', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Baghdad', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Baghdad', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇮🇶', 'High-performance VPS hosting in Baghdad with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Bahrain', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Bahrain', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Bahrain', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇧🇭', 'High-performance VPS hosting in Bahrain with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Doha', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Doha', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Doha', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇶🇦', 'High-performance VPS hosting in Doha with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Dubai', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Dubai', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Dubai', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇦🇪', 'High-performance VPS hosting in Dubai with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Istanbul', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Istanbul', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Istanbul', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇹🇷', 'High-performance VPS hosting in Istanbul with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Jeddah', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Jeddah', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Jeddah', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Jeddah with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Kuwait City', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Kuwait City', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Kuwait City', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇰🇼', 'High-performance VPS hosting in Kuwait City with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Muscat', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Muscat', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Muscat', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇴🇲', 'High-performance VPS hosting in Muscat with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Riyadh', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Riyadh', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Riyadh', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Middle East', '🇸🇦', 'High-performance VPS hosting in Riyadh with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- North America
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Mexico City', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Mexico City', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Mexico City', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'North America', '🇲🇽', 'High-performance VPS hosting in Mexico City with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Silicon Valley', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Silicon Valley', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Silicon Valley', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'North America', '🇺🇸', 'High-performance VPS hosting in Silicon Valley with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Washington', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Washington', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Washington', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'North America', '🇺🇸', 'High-performance VPS hosting in Washington with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- Oceania
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Sydney', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Sydney', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Sydney', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Oceania', '🇦🇺', 'High-performance VPS hosting in Sydney with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- South America
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Bogota', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Bogota', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Bogota', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South America', '🇨🇴', 'High-performance VPS hosting in Bogota with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Buenos Aires', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Buenos Aires', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Buenos Aires', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South America', '🇦🇷', 'High-performance VPS hosting in Buenos Aires with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Santiago', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Santiago', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Santiago', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South America', '🇨🇱', 'High-performance VPS hosting in Santiago with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'São Paulo', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'São Paulo', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'São Paulo', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South America', '🇧🇷', 'High-performance VPS hosting in São Paulo with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- South Asia
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Dhaka', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Dhaka', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Dhaka', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South Asia', '🇧🇩', 'High-performance VPS hosting in Dhaka with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Karachi', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Karachi', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Karachi', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South Asia', '🇵🇰', 'High-performance VPS hosting in Karachi with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Kathmandu', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Kathmandu', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Kathmandu', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South Asia', '🇳🇵', 'High-performance VPS hosting in Kathmandu with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Mumbai', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Mumbai', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Mumbai', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'South Asia', '🇮🇳', 'High-performance VPS hosting in Mumbai with dedicated resources and enterprise-grade infrastructure.', 'Pro');

-- Southeast Asia
INSERT INTO public.hosting_plans (name, category, subcategory, ram, cpu, storage, bandwidth, location, os_type, price_monthly, price_yearly, order_url, visible, sort_order, region, flag_icon, page_description, plan_type) VALUES
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Bangkok', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Bangkok', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Bangkok', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇹🇭', 'High-performance VPS hosting in Bangkok with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Hanoi', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Hanoi', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Hanoi', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Hanoi with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Ho Chi Minh City', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Ho Chi Minh City', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Ho Chi Minh City', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇻🇳', 'High-performance VPS hosting in Ho Chi Minh City with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Jakarta', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Jakarta', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Jakarta', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇮🇩', 'High-performance VPS hosting in Jakarta with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Kuala Lumpur', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Kuala Lumpur', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Kuala Lumpur', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇲🇾', 'High-performance VPS hosting in Kuala Lumpur with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Manila', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Manila', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Manila', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇵🇭', 'High-performance VPS hosting in Manila with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Phnom Penh', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Phnom Penh', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Phnom Penh', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇰🇭', 'High-performance VPS hosting in Phnom Penh with dedicated resources and enterprise-grade infrastructure.', 'Pro'),
('Basic VPS', 'VPS', NULL, '2GB RAM', '1 vCPU', '30GB SSD', '1TB', 'Yangon', 'Linux', 9.99, 7.99, 'https://portal.qiwhost.com/login', TRUE, 10, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon with dedicated resources and enterprise-grade infrastructure.', 'Basic'),
('Standard VPS', 'VPS', NULL, '4GB RAM', '2 vCPU', '60GB SSD', '2TB', 'Yangon', 'Linux', 19.99, 15.99, 'https://portal.qiwhost.com/login', TRUE, 20, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon with dedicated resources and enterprise-grade infrastructure.', 'Standard'),
('Pro VPS', 'VPS', NULL, '8GB RAM', '4 vCPU', '120GB SSD', '4TB', 'Yangon', 'Linux', 39.99, 31.99, 'https://portal.qiwhost.com/login', TRUE, 30, 'Southeast Asia', '🇲🇲', 'High-performance VPS hosting in Yangon with dedicated resources and enterprise-grade infrastructure.', 'Pro');
```